python map_rl_from_example/ppo_map.py \
    --env_id=PickYCBSequential-v1 \
    --control_mode=pd_joint_vel \
    --exp_name=YCB_sequential_xarm6_ppo_map_dino_zero \
    --num_envs=100 \
    --num_eval_envs=12 \
    --eval_freq=20 \
    --total_timesteps=30_000_000 \
    --num_steps=200 \
    --num_eval_steps=200 \
    --gamma=0.9 \
    --ent_coef=1e-3 \
    --learning_rate=3e-4 \
    --vision_encoder=dino \
    --capture-video \
    --track \
    --wandb_project_name "PPO-RL-Map" \
    --use_map \
    --checkpoint "save_checkpoint/2_object_cam_aligned_image.pt" \
    --load_actor_logstd
    # --start_condition_map
