python sanity_check/ppo_state.py \
    --env_id=PickYCBSequential-v1 \
    --control_mode=pd_joint_vel \
    --exp_name=YCB_sequential_xarm6_ppo_state \
    --num_envs=100 \
    --num_eval_envs=20 \
    --eval_freq=20 \
    --total_timesteps=100_000_000 \
    --num_steps=500 \
    --num_eval_steps=500 \
    --gamma=0.9 \
    --gae_lambda=0.9 \
    --update_epochs=4 \
    --learning_rate=3e-4 \
    --capture-video \
    --track \
    --wandb_project_name "PPO-RL-Map" \
    --checkpoint_path "runs/YCB_sequential_xarm6_ppo_state/ckpt_101.pt"